library(raster)

raster1 <- raster("D:/KULIAH ZAI MAGISTER PENGINDERAAN JAUH/BISMILLAH THESIS/SCRIPT R TREND/HASIL/SEN_SLOPE_TREND_BANDUNG_HUJAN.tif")
raster2 <- raster("D:/KULIAH ZAI MAGISTER PENGINDERAAN JAUH/BISMILLAH THESIS/SCRIPT R TREND/HASIL/SEN_SLOPE_TREND_BANDUNG_KEMARAU.tif")
raster3 <- raster("D:/KULIAH ZAI MAGISTER PENGINDERAAN JAUH/BISMILLAH THESIS/SCRIPT R TREND/HASIL/SEN_SLOPE_TREND_SEMARANG_HUJAN.tif")
raster4 <- raster("D:/KULIAH ZAI MAGISTER PENGINDERAAN JAUH/BISMILLAH THESIS/SCRIPT R TREND/HASIL/SEN_SLOPE_TREND_SEMARANG_KEMARAU.tif")

# Customize plot settings
par(mfrow=c(2, 2))
plot(raster1, main="TREND_BANDUNG_HUJAN", col=terrain.colors(100))
plot(raster2, main="TREND_BANDUNG_KEMARAU", col=terrain.colors(100))
plot(raster3, main="TREND_SEMARANG_HUJAN", col=terrain.colors(100))
plot(raster4, main="TREND_SEMARANG_KEMARAU", col=terrain.colors(100))


